# Make sure to run the README.md usage example on commits.
dist: trusty
language: python
cache: pip
install: pip install tensorflow==1.2.0rc1
script: python -c 'exec(open("README.md").read().split("```")[1][6:])'
